---
- hosts: server2
  tasks:
  
  - name: "Create web root directory"
    file: 
      path: /home/vagrant/html/
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755
  
  - name: "Copy welcome page"
    copy:  
      src: /vagrant/ansible/playbooks/files/index.html
      dest: /home/vagrant/html/index.html
      owner: vagrant
      group: vagrant
      mode: 0644
  
  - name: "start nginx container"
    docker_container: 
      name: "nginx"
      image: nginx
      volumes:
      - "/home/vagrant/html:/usr/share/nginx/html:ro"
      published_ports:
      - "80:80"
      restart_policy: unless-stopped
      restart: True
    become: True

  - name: register nginx service
    consul: 
      service_name: nginx
      service_port: "80"
      service_address: "{{ansible_host}}"
      interval: 2m
      http: http://{{ansible_host}}
