---
# this playbook allows for memory limitations, When
# running docker on ubuntu.
# On ubuntu memory cgroup is not enabled by default
- hosts: managed_nodes
  tasks:
  - name: Grub | update Linux Cmd line
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
    register: grub_default
    become: True

  - block:
    - name: GRUB | update
      command: "update-grub"
      become: True
    - name: GRUB | reboot
      command: /sbin/shutdown -r +1
      become: True
    - name: GRUB | wait for machine to come back up
      local_action: wait_for host="{{ ansible_host }}" port=22 timeout=300 delay=90
      become: True
    when: grub_default | changed
