- name: restart postgresql container
  docker_container:
    name: "{{ postgresql_service_name }}"
    state: started
    restart: True
    restart_policy: on-failure
    restart_retries: 5
  become: True
