---
- hosts: controller
  tasks:
  - name: "install tools"
    become: True
    package:
      name: "{{ item }}"
    with_items:
    - tar
    - unzip

- import_playbook: playbooks/pki.yml
  when: pki_create == True

- import_playbook: playbooks/fix-mirror.yml
- import_playbook: playbooks/base-config.yml
- import_playbook: playbooks/servicediscovery.yml
- import_playbook: playbooks/vaultserver.yml
- import_playbook: playbooks/vaultsetup.yml
# elasticsearch cluster (used by graylog / gitlab)
- import_playbook: playbooks/es.yml
# mongodb replica set (used by graylog)
- import_playbook: playbooks/mongodb.yml
- import_playbook: playbooks/graylog.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/clusterscheduler.yml
- import_playbook: playbooks/monitoring.yml
- import_playbook: playbooks/nomad-ui.yml
