---
- import_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- import_tasks: install.yml
  tags: [postgresql, postgresql-install]

# create users, databases
# and assign users privileges on databases
- include_tasks: users.yml
  tags: [postgresql, postgresql-users]
- include_tasks: databases.yml
  tags: [postgresql, postgresql-databases]
- include_tasks: users_privileges.yml
  tags: [postgresql, postgresql-user_privileges]
